; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

; ===== CONFIGURACION BASE =====
[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_port = COM3

lib_deps = 
	earlephilhower/ESP8266Audio@^1.9.7
	chris--a/Keypad@^3.1.1
	arduino-libraries/Stepper@^1.1.3


; ====== MAIN ======
[env:main]
extends = env:upesy_wroom
build_src_filter =
    +<main.cpp>


; ====== CLIENT CONTROL ======
[env:client]
extends = env:upesy_wroom
build_src_filter =
    +<clientControl.cpp>


; ====== SERVER CONTROL ======
[env:server]
extends = env:upesy_wroom
build_src_filter =
    +<serverControl.cpp>


; ====== KEY CONTROL ======
[env:key]
extends = env:upesy_wroom
build_src_filter =
    +<keycontrol.cpp>


; ====== MAC ADDRESS ======
[env:mac]
extends = env:upesy_wroom
build_src_filter =
    +<mac.cpp>


; ====== SERVO ======
[env:servo]
extends = env:upesy_wroom
build_src_filter =
    +<servo.cpp>


; ====== SERVO 2 ======
[env:servo2]
extends = env:upesy_wroom
build_src_filter =
    +<servo2.cpp>


; ====== SONIDO ======
[env:sonido]
extends = env:upesy_wroom
build_src_filter =
    +<sonido.cpp>